// QCovid® Calculation Engine is Copyright © 2020 Oxford University Innovation Limited.
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY.  See the
// GNU Affero General Public License for more details.
// 
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
// 
// PLEASE NOTE:
// In its compiled form, QCovid@ Calculation Engine is a Class I Medical Device and
// is covered by the Medical Device Regulations 2002 (as amended).
// 
// Modification of the source code and subsequently placing that modified code on the market
// may make that person/entity a legal manufacturer of a medical device and so
// subject to the requirements listed in Medical Device Regulations 2002 (as amended).
// 
// Failure to comply with these regulations (for example, failure to comply with the relevant
// registration requirements or failure to meet the relevant essential requirements)
// may result in prosecution and a penalty of an unlimited fine and/or 6 months’ imprisonment.
// 
// This source code version of QCovid® Calculation Engine is provided as is, and
// has not been certified for clinical use, and must not be used for supporting or informing clinical decision-making.

/* 
 * This file has been auto-generated using ClinRisk Ltd's tools.
 * XML source: OX100_status3_20_1.xml
 * STATA dta time stamp: 4 Jul 2020 14:00
 * .NET file create date: Tue  4 Aug 2020 13:37:16 BST
 */

using System;
using System.IO;
using System.Collections;

using CRStandardDefinitions;

namespace ClinRiskAutogenerated
{
    internal class OX100_status3_20_1
    {
        public class Result
        {
            public string status;
            public Double? score;

            public Result()
            {
                status = "undefined";
                score = null;
            }
        }

        // helper methods for the validation method
        private bool is_boolean(int b)
        {
            bool result = false;
            if (b == 1 || b == 0)
            {
                result = true;
            }
            return result;
        }

        private bool d_in_range(double x, double min, double max)
        {
            return !(x < min || x > max);
        }

        private bool i_in_range(int x, int min, int max)
        {
            return !(x < min || x > max);
        }

        public bool ok = true;
        public ArrayList errorList = new ArrayList();
        public bool estimate = false;
        public ArrayList estimateList = new ArrayList();

        private bool validateIntsAndDoubles(ref int age, bool b2_82, bool b2_leukolaba, bool b2_prednisolone, bool b_AF, bool b_CCF, bool b_asthma, bool b_bloodcancer, bool b_cerebralpalsy, bool b_chd, bool b_cirrhosis, bool b_congenheart, bool b_copd, bool b_dementia, bool b_epilepsy, bool b_fracture4, bool b_neurorare, bool b_parkinsons, bool b_pulmhyper, bool b_pulmrare, bool b_pvd, bool b_ra_sle, bool b_respcancer, bool b_semi, bool b_sicklecelldisease, bool b_stroke, DiabetesCat diabetes_cat, bool b_vte, ref double bmi, Chemocat chemocat, Ethnicity ethnicity, Homecat homecat, Learncat learncat, bool p_marrow6, bool p_radio6, bool p_solidtransplant, Renalcat renalcat, ref int surv, ref double town)
        {
            ok = true;
            estimate = false;
            errorList.Clear();
            estimateList.Clear();

            if (!i_in_range(age, 19, 100))
            {
                ok = false;
                errorList.Add("age must be in range (19,100)");
            }
            if (!d_in_range(bmi, 15, 47))
            {
                estimate = true;
                if (bmi < 15)
                {
                    bmi = 15;
                }
                if (bmi > 47)
                {
                    bmi = 47;
                }
                estimateList.Add("bmi adjusted to lie in range (15,47)");
            }
            if (!i_in_range(surv, 1, 90))
            {
                ok = false;
                errorList.Add("surv must be in range (1,90)");
            }
            if (!d_in_range(town, -8, 12))
            {
                estimate = true;
                if (town < -8)
                {
                    town = -8;
                }
                if (town > 12)
                {
                    town = 12;
                }
                estimateList.Add("town adjusted to lie in range (-8,12)");
            }
            /*  return validity */
            return ok;
        }

        /* status3 */

        static private double status3_male_raw(
            int age, int b2_82, int b2_leukolaba, int b2_prednisolone, int b_AF, int b_CCF, int b_asthma, int b_bloodcancer, int b_cerebralpalsy, int b_chd, int b_cirrhosis, int b_congenheart, int b_copd, int b_dementia, int b_epilepsy, int b_fracture4, int b_neurorare, int b_parkinsons, int b_pulmhyper, int b_pulmrare, int b_pvd, int b_ra_sle, int b_respcancer, int b_semi, int b_sicklecelldisease, int b_stroke, int b_type1, int b_type2, int b_vte, double bmi, int chemocat, int ethrisk, int homecat, int learncat, int p_marrow6, int p_radio6, int p_solidtransplant, int renalcat, int surv, double town
        )
        {
            double[] survivor = {
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0.999998033046722,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0.999956965446472
            };

            /* The conditional arrays */

            double[] Ichemocat = {
                0,
                0.5518382023402614855456250,
                1.2521892539965664425949399,
                1.2136983258866618218263511
            };
            double[] Iethrisk = {
                0,
                0,
                0.4612255535316009957824690,
                0.6111266423098750122377965,
                0.8204730544167745387440505,
                0.7014941739425393230078498,
                0.7240940102093914587655377,
                1.1094023093836316018467869,
                0.9042387414289448921422832,
                0.7111426262631623806953485
            };
            double[] Ihomecat = {
                0,
                1.4544904405508778388878000,
                0.4426122079730733793745401
            };
            double[] Ilearncat = {
                0,
                0.3038620602034622364406857,
                2.2820367212000198797738904
            };
            double[] Irenalcat = {
                0,
                0,
                0.1624549376621728935532474,
                0.6050038962863354408128203,
                0.8751467115376150296413016,
                1.2993052354424052818870905,
                1.1624518358657724981242154
            };

            /* Applying the fractional polynomial transforms */
            /* (which includes scaling)                      */

            double dage = age;
            dage = dage / 10;
            double age_1 = dage;
            double age_2 = Math.Pow(dage, 3);
            double dbmi = bmi;
            dbmi = dbmi / 10;
            double bmi_1 = Math.Pow(dbmi, -.5);
            double bmi_2 = Math.Pow(dbmi, -.5) * Math.Log(dbmi);

            /* The normalisation coefficients */

            double mage_1 = 4.770704746246338;
            double mage_2 = 108.579444885253906;
            double mbmi_1 = 0.613678753376007;
            double mbmi_2 = 0.599298655986786;
            double mtown = 0.436863929033279;

            /* Centring the continuous variables */

            age_1 = age_1 - mage_1;
            age_2 = age_2 - mage_2;
            bmi_1 = bmi_1 - mbmi_1;
            bmi_2 = bmi_2 - mbmi_2;
            town = town - mtown;

            /* Start of Sum */
            double a = 0;

            /* The conditional sums */

            a += Ichemocat[chemocat];
            a += Iethrisk[ethrisk];
            a += Ihomecat[homecat];
            a += Ilearncat[learncat];
            a += Irenalcat[renalcat];

            /* The continuous coefficients */

            double cage_1 = 1.4547532388624053734105246;
            double cage_2 = -0.0028280265297625597521736;
            double cbmi_1 = -22.0609948165960112476113864;
            double cbmi_2 = -20.3035078034241216471400548;
            double ctown = 0.0812689785693790078813237;

            /* Sum from continuous values */

            a += age_1 * cage_1;
            a += age_2 * cage_2;
            a += bmi_1 * cbmi_1;
            a += bmi_2 * cbmi_2;
            a += town * ctown;

            /* The boolean coefficients */

            double cb2_82 = 0.4591322211314322609965188;
            double cb2_leukolaba = 0.0412503496956075910162554;
            double cb2_prednisolone = 0.3626076782717908564279696;
            double cb_AF = 0.1052111096824691061080159;
            double cb_CCF = 0.3396973581366389827174146;
            double cb_asthma = 0.0321078769888719015024314;
            double cb_bloodcancer = 0.2516787141016778583946234;
            double cb_cerebralpalsy = 1.0196367443019023202310791;
            double cb_chd = 0.1185398586465893217001266;
            double cb_cirrhosis = 0.2579778953047697220846146;
            double cb_congenheart = 0.0297033412293931098346889;
            double cb_copd = 0.2247771466899423364882438;
            double cb_dementia = 1.1427890629158352631122852;
            double cb_epilepsy = 0.4706338398323707261639015;
            double cb_fracture4 = 0.3447414553384527402535298;
            double cb_neurorare = 0.6862474948256528373136121;
            double cb_parkinsons = 0.6584837103149563386494947;
            double cb_pulmhyper = 0.3845567043397818407513000;
            double cb_pulmrare = 0.1846607906556500255934594;
            double cb_pvd = 0.3234029467753249398320747;
            double cb_ra_sle = 0.0152761200100454391098692;
            double cb_respcancer = 0.2405175355951279514421515;
            double cb_semi = 0.2342064563503280238965232;
            double cb_sicklecelldisease = 1.4829018816463233054747661;
            double cb_stroke = 0.2126223941662605809721498;
            double cb_type1 = 1.7655772899003154829955520;
            double cb_type2 = 1.5551685093805573956160515;
            double cb_vte = 0.3075001687704595476624547;
            double cp_marrow6 = 1.8089884245023548636766009;
            double cp_radio6 = 0.7391718905778561499175794;
            double cp_solidtransplant = 0.5444438235973578787962879;

            /* Sum from boolean values */

            a += b2_82 * cb2_82;
            a += b2_leukolaba * cb2_leukolaba;
            a += b2_prednisolone * cb2_prednisolone;
            a += b_AF * cb_AF;
            a += b_CCF * cb_CCF;
            a += b_asthma * cb_asthma;
            a += b_bloodcancer * cb_bloodcancer;
            a += b_cerebralpalsy * cb_cerebralpalsy;
            a += b_chd * cb_chd;
            a += b_cirrhosis * cb_cirrhosis;
            a += b_congenheart * cb_congenheart;
            a += b_copd * cb_copd;
            a += b_dementia * cb_dementia;
            a += b_epilepsy * cb_epilepsy;
            a += b_fracture4 * cb_fracture4;
            a += b_neurorare * cb_neurorare;
            a += b_parkinsons * cb_parkinsons;
            a += b_pulmhyper * cb_pulmhyper;
            a += b_pulmrare * cb_pulmrare;
            a += b_pvd * cb_pvd;
            a += b_ra_sle * cb_ra_sle;
            a += b_respcancer * cb_respcancer;
            a += b_semi * cb_semi;
            a += b_sicklecelldisease * cb_sicklecelldisease;
            a += b_stroke * cb_stroke;
            a += b_type1 * cb_type1;
            a += b_type2 * cb_type2;
            a += b_vte * cb_vte;
            a += p_marrow6 * cp_marrow6;
            a += p_radio6 * cp_radio6;
            a += p_solidtransplant * cp_solidtransplant;

            /* The interaction coefficients */

            double cage_1_b_type2 = -0.5325370730252168005591784;
            double cage_2_b_type2 = 0.0013434948852218797209906;

            /* Sum from interaction terms */

            a += age_1 * b_type2 * cage_1_b_type2;
            a += age_2 * b_type2 * cage_2_b_type2;

            /* Calculate the score itself */
            double score = 100.0 * (1 - Math.Pow(survivor[surv], Math.Exp(a)));
            return score;
        }

        public Result status3_male(
            int age, bool b2_82, bool b2_leukolaba, bool b2_prednisolone, bool b_AF, bool b_CCF, bool b_asthma, bool b_bloodcancer, bool b_cerebralpalsy, bool b_chd, bool b_cirrhosis, bool b_congenheart, bool b_copd, bool b_dementia, bool b_epilepsy, bool b_fracture4, bool b_neurorare, bool b_parkinsons, bool b_pulmhyper, bool b_pulmrare, bool b_pvd, bool b_ra_sle, bool b_respcancer, bool b_semi, bool b_sicklecelldisease, bool b_stroke, DiabetesCat diabetes_cat, bool b_vte, double bmi, Chemocat chemocat, Ethnicity ethnicity, Homecat homecat, Learncat learncat, bool p_marrow6, bool p_radio6, bool p_solidtransplant, Renalcat renalcat, int surv, double town
        )
        {
            Result result = new Result();
            bool validInputs = validateIntsAndDoubles(ref age, b2_82, b2_leukolaba, b2_prednisolone, b_AF, b_CCF, b_asthma, b_bloodcancer, b_cerebralpalsy, b_chd, b_cirrhosis, b_congenheart, b_copd, b_dementia, b_epilepsy, b_fracture4, b_neurorare, b_parkinsons, b_pulmhyper, b_pulmrare, b_pvd, b_ra_sle, b_respcancer, b_semi, b_sicklecelldisease, b_stroke, diabetes_cat, b_vte, ref bmi, chemocat, ethnicity, homecat, learncat, p_marrow6, p_radio6, p_solidtransplant, renalcat, ref surv, ref town);
            if (validInputs)
            {
                result.status = "ok";
                if (estimate)
                {
                    result.status = "estimate:";
                    foreach (Object obj in estimateList)
                    {
                        string s = (string)obj;
                        s = s.Replace(",", " to ");
                        result.status += s + ";";
                    }
                }
            }
            else
            {
                result.status = "error:";
                foreach (Object obj in errorList)
                {
                    string s = (string)obj;
                    s = s.Replace(",", " to ");
                    result.status += s + ";";
                }
                result.score = null;
                return result;
            }

            double tmp = status3_male_raw(
                age,    // age must lie in range (19 .. 100)
                Utilities.boolToInt(b2_82),
                Utilities.boolToInt(b2_leukolaba),
                Utilities.boolToInt(b2_prednisolone),
                Utilities.boolToInt(b_AF),
                Utilities.boolToInt(b_CCF),
                Utilities.boolToInt(b_asthma),
                Utilities.boolToInt(b_bloodcancer),
                Utilities.boolToInt(b_cerebralpalsy),
                Utilities.boolToInt(b_chd),
                Utilities.boolToInt(b_cirrhosis),
                Utilities.boolToInt(b_congenheart),
                Utilities.boolToInt(b_copd),
                Utilities.boolToInt(b_dementia),
                Utilities.boolToInt(b_epilepsy),
                Utilities.boolToInt(b_fracture4),
                Utilities.boolToInt(b_neurorare),
                Utilities.boolToInt(b_parkinsons),
                Utilities.boolToInt(b_pulmhyper),
                Utilities.boolToInt(b_pulmrare),
                Utilities.boolToInt(b_pvd),
                Utilities.boolToInt(b_ra_sle),
                Utilities.boolToInt(b_respcancer),
                Utilities.boolToInt(b_semi),
                Utilities.boolToInt(b_sicklecelldisease),
                Utilities.boolToInt(b_stroke),
                Utilities.diabetescatToType1(diabetes_cat),
                Utilities.diabetescatToType2(diabetes_cat),
                Utilities.boolToInt(b_vte),
                bmi,    // bmi must lie in range (15 .. 47)
                Utilities.chemocatToInt(chemocat),
                Utilities.ethnicityToEthrisk(ethnicity),
                Utilities.homecatToInt(homecat),
                Utilities.learncatToInt(learncat),
                Utilities.boolToInt(p_marrow6),
                Utilities.boolToInt(p_radio6),
                Utilities.boolToInt(p_solidtransplant),
                Utilities.renalcatToInt(renalcat),
                surv,   // surv must lie in range (1 .. 90)
                town    // town must lie in range (-8 .. 12)
            );
            tmp = Math.Round(tmp * 1000000.0) / 1000000.0;
            result.score = tmp;

            return result;
        }

        /* End of status3 */

    }
}
